module.exports = {
  roots: ['<rootDir>/src'],
  collectCoverageFrom: [
    '<rootDir>/src/**/*.ts',
    '!**/*.spec.ts',
    '!<rootDir>/src/**/*.dto.ts',
    '!<rootDir>/src/**/*.mock.ts',
    '!<rootDir>/src/**/*.filter.ts',
    '!<rootDir>/src/**/*.config.ts',
    '!<rootDir>/src/**/*.repository.ts',
    '!<rootDir>/src/**/*.index.ts',
    '!<rootDir>/src/common/**/*.ts',
    '!<rootDir>/src/**/migrations/**/*.ts',
    '!<rootDir>/src/**/*.module.ts',
    '!<rootDir>/src/**/*.controller.ts',
    '!<rootDir>/src/**/*.entity.ts',
    '!<rootDir>/src/**/*.type.ts',
    '!<rootDir>/src/**/*.enum.ts',
    '!<rootDir>/src/main.ts',
    '!<rootDir>/src/main.ts',
    '!<rootDir>/src/global.ts',
  ],
  coverageDirectory: 'coverage',
  testEnvironment: 'node',
  coverageThreshold: {
    global: {
      branches: 80,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  transform: {
    '.+\\.ts$': 'ts-jest',
  },
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
  },
  moduleFileExtensions: ['js', 'json', 'ts'],
  resetMocks: true,
  clearMocks: true,
};
